version: '3'

services:
  db:
    image: mariadb
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./migrations/:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_ROOT_PASSWORD: 'changeme' # init setting.

  app:
    build: .
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
    ports:  # debugging purpose only, don't expose on production
      - '80:80'
    environment:
      DB_PASSWORD: 'changeme' # init setting.
