version: '3'

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - ./migrations/:/docker-entrypoint-initdb.d/:ro
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  app:
    build: .
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
    ports:  # debugging purpose only, don't expose on production
      - '80:80'
    env_file: .env
    environment:
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ap-northeast-2